### ISSUE TITLE
Receiving Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Rest.ServiceClientCredentials> Microsoft.Rest.Azure.Authentication.UserTokenProvider.LoginSilentAsync

### ISSUE THREAD

**Issue by qamessenger** [Azure/azure-libraries-for-net#282]
Hi I am trying to use the following Code 
Nuget  Version:
 <package id="Microsoft.Azure.Management.AppService.Fluent" version="1.9.1" targetFramework="net471" />  and all the dependencies.

Code Snippet:

 var credentials = SdkContext.AzureCredentialsFactory.FromFile($@"MyAzure.properties");
 var azureMgtClient = Azure
        .Configure()
        .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
         .Authenticate(credentials)
         .WithSubscription(_subscriptionId);
                     
Exception occurs here=>  var vm = azureMgtClient.VirtualMachines.GetByResourceGroup("resourceGroup", "VmName");

            vm.Start();

I am receiving the exception:

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Rest.ServiceClientCredentials> Microsoft.Rest.Azure.Authentication.UserTokenProvider.LoginSilentAsync(System.String, System.String, System.String, System.String, Microsoft.Rest.Azure.Authentication.ActiveDirectoryServiceSettings, Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache)'.
  Source=Microsoft.Azure.Management.ResourceManager.Fluent
  StackTrace:
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__23.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesOperations.<GetWithHttpMessagesAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesOperationsExtensions.<GetAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesImpl.<GetInnerByGroupAsync>d__49.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.<GetByResourceGroupAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.GetByResourceGroup(String groupName, String name)

**Comment by hovsepm** [comment]
@qamessenger Which version are you using?

**Comment by hovsepm** [comment]
And which version of ADAL are you using?

**Comment by hovsepm** [comment]
And what is your project target .Net framework?

**Comment by JREndeanMSFT** [comment]
@qamessenger what version of Microsoft.Rest.ClientRuntime.Azure.Authentication do you have downloaded? I had a similar exception happen when I upgraded that to 2.3.3 (after upgrading the Fluent nugets to 1.9.1). I rolled back to 2.3.2 and that seems to work. I have not had time to investigate the exception I saw any further though.

**Comment by qamessenger** [comment]
HI,

I am using the following 
Microsoft.Rest.ClientRuntime.Azure.Authentication version 2.3.3 
Microsoft.Rest.ClientRuntime version 2.3.11 
.Net Framework version for my project is 4.7.1 
for ADAL the package was not required when installing Fluent 1.9.1.

Greg

**Comment by chriswgr** [comment]
@avantida The exact same thing is happening to me.

I used ILDasm to compare the methods of Microsoft.Azure.Rest.Authentication.UserTokenProvider between v2.3.3.0 & v2.3.1.0.  The newer version (2.3.3.0) has far fewer methods.

**Comment by isaacabraham** [comment]
Confirmed, I'm seeing the same thing here. Downgrading to 2.3.2 fixes the problem for me.

**Comment by isaacabraham** [comment]
@hovsepm which package version is this?

**Comment by hovsepm** [comment]
@isaacabraham 1.15.1

**Comment by isaacabraham** [comment]
@hovsepm I don't understand. The nuget package is for Microsoft.Rest.ClientRuntime.Azure.Authentication is 2.3.2.

**Comment by hovsepm** [comment]
@isaacabraham the issue is fixed in Microsoft.Azure.Management.Fluent v1.5.1. We reference latest Microsoft.Rest.ClientRuntime.Azure.Authentication 2.3.4 which has the fix in this area as well.

**Comment by isaacabraham** [comment]
Ah great ok. Is 1.5.1 of Fluent compatible with earlier versions of Azure Auth as well? Like 2.3.2 etc?

**Comment by hovsepm** [comment]
no. We require minimum version of Azure Auth 2.3.4

**Comment by isaacabraham** [comment]
Great, thanks for the clarification.

**Comment by rubyhog** [comment]
Hi hovsepm, I have the same issue. There are only two methods: CreateCredentialsFromCache / LoginByDeviceCodeAsync for Microsoft.Rest.Azure.Authentication.UserTokenProvider on version 2.3.4
Even I installed Microsoft.Azure.Management.Fluent 1.15.1 by Nuget after I saw this post, still can't see LoginSilentAsync method. ( Actaully previously 2.3.2's method names are CreateCredentialsFromCache / LoginWithPromptAsync / LoginSilentAsync ) 
How to use Microsoft.Azure.Management.Fluent 1.15.1 for this? thanks a lot.

**Comment by rubyhog** [comment]
Target .Net framework 4.6.1 and 4.6.2

**Comment by austincrft** [comment]
I am also seeing the same error as @rubyhog, I think this should be reopened.

**Comment by praries880** [comment]
@austincrft More info on why this scenario does  not work anymore : https://github.com/Azure/azure-sdk-for-net/issues/4316

Try using the suggestions in : https://github.com/Azure/azure-libraries-for-net/blob/master/AUTH.md
